//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Core.Infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.coursestudent = new HashSet<coursestudent>();
            this.enrollment = new HashSet<enrollment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<coursestudent> coursestudent { get; set; }
        public virtual ICollection<enrollment> enrollment { get; set; }
    }
}
